name: Destroy infrastructure on aws

on:
  workflow_dispatch:

jobs:
  destroy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
        working-directory: lambda
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          terraform destroy -auto-approve \
            -var "email=${{ secrets.EMAIL }}" \
            -var "access_key=${{ secrets.ACCESS_KEY }}" \
            -var "secret_key=${{ secrets.SECRET_KEY }}" \
        working-directory: infrastructure