name: Destroy infrastructure on aws

on:
  workflow_dispatch:
    branches: ["main"]

jobs:
  destroy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: lambda
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var "schedule_interval=$(( ${{ env.SCHEDULE_INTERVAL }} + 0 ))" \
            -var "phone_number=${{ env.PHONE_NUMBER }}" \
            -var "access_key=${{ secrets.ACCESS_KEY }}" \
            -var "secret_key=${{ secrets.SECRET_KEY }}" \
            -var "shop_region=${{ env.SHOP_REGION }}" \
            -var "pi_model=${{ env.PI_MODEL }}"
        working-directory: infrastructure